[package]
name = "stef-build"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
miette.workspace = true
proc-macro2 = { version = "1.0.66", default-features = false }
quote = { version = "1.0.33", default-features = false }
stef-parser = { path = "../stef-parser" }
thiserror = "1.0.48"

[dev-dependencies]
indoc = "2.0.3"
insta = { version = "1.31.0", features = ["glob"] }
pretty_assertions = "1.4.0"
prettyplease = "0.2.15"
stef = { path = "../stef" }
syn = "2.0.32"
