[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com"]
edition = "2021"
rust-version = "1.71"
readme = "README.md"
homepage = "https://github.com/dnaka91/stef"
repository = "https://github.com/dnaka91/stef"
license = "MIT"

[workspace.dependencies]
color-eyre = { version = "0.6.2", default-features = false }
miette = "5.10.0"

[profile.release]
lto = true
strip = true
