[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com"]
edition = "2021"
rust-version = "1.76"
readme = "README.md"
homepage = "https://github.com/dnaka91/mabo"
repository = "https://github.com/dnaka91/mabo"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"
rust_2018_idioms = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
all = "deny"
pedantic = "warn"
clone_on_ref_ptr = "warn"

[workspace.dependencies]
anstream = "0.6.13"
anstyle = "1.0.6"
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive", "wrap_help"] }
glob = "0.3.1"
indoc = "2.0.4"
insta = { version = "1.35.1", features = ["glob"] }
miette = { version = "7.1.0", default-features = false }
mimalloc = "0.1.39"
proc-macro2 = { version = "1.0.78", default-features = false }
quote = { version = "1.0.35", default-features = false }
rustc-hash = "1.1.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
syn = "2.0.52"
thiserror = "1.0.57"

[profile.release]
lto = "thin"
strip = true
