[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com"]
edition = "2021"
rust-version = "1.71"
readme = "README.md"
homepage = "https://github.com/dnaka91/stef"
repository = "https://github.com/dnaka91/stef"
license = "MIT"

[workspace.dependencies]
color-eyre = { version = "0.6.2", default-features = false }
indoc = "2.0.4"
insta = { version = "1.34.0", features = ["glob"] }
miette = "5.10.0"
mimalloc = "0.1.39"
proc-macro2 = { version = "1.0.69", default-features = false }
quote = { version = "1.0.33", default-features = false }
syn = "2.0.38"
thiserror = "1.0.49"

[profile.release]
lto = true
strip = true
