[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com"]
edition = "2024"
rust-version = "1.85"
readme = "README.md"
homepage = "https://github.com/dnaka91/mabo"
repository = "https://github.com/dnaka91/mabo"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"
rust_2018_idioms = { level = "deny", priority = -1 }
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
clone_on_ref_ptr = "warn"

[workspace.dependencies]
anstream = "0.6.18"
anstyle = "1.0.10"
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive", "wrap_help"] }
glob = "0.3.2"
indoc = "2.0.5"
insta = { version = "1.42.1", features = ["glob"] }
miette = { version = "7.5.0", default-features = false }
mimalloc = "0.1.43"
proc-macro2 = { version = "1.0.93", default-features = false }
quote = { version = "1.0.38", default-features = false }
rustc-hash = "2.1.1"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
syn = "2.0.98"
thiserror = "2.0.11"

[profile.release]
lto = "thin"
strip = true
