[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com"]
edition = "2021"
rust-version = "1.71"
readme = "README.md"
homepage = "https://github.com/dnaka91/stef"
repository = "https://github.com/dnaka91/stef"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"
rust_2018_idioms = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
all = "deny"
pedantic = "warn"
clone_on_ref_ptr = "warn"

[workspace.dependencies]
anyhow = "1.0.76"
clap = { version = "4.4.11", features = ["derive", "wrap_help"] }
color-eyre = { version = "0.6.2", default-features = false }
glob = "0.3.1"
indoc = "2.0.4"
insta = { version = "1.34.0", features = ["glob"] }
miette = "5.10.0"
mimalloc = "0.1.39"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
proc-macro2 = { version = "1.0.71", default-features = false }
quote = { version = "1.0.33", default-features = false }
syn = "2.0.42"
thiserror = "1.0.51"

[profile.release]
lto = true
strip = true
