[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Dominik Nakamura <dnaka91@gmail.com"]
edition = "2021"
rust-version = "1.80"
readme = "README.md"
homepage = "https://github.com/dnaka91/mabo"
repository = "https://github.com/dnaka91/mabo"
license = "MIT"

[workspace.lints.rust]
unsafe_code = "forbid"
rust_2018_idioms = { level = "deny", priority = -1 }
missing_docs = "warn"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "warn", priority = -1 }
clone_on_ref_ptr = "warn"

[workspace.dependencies]
anstream = "0.6.18"
anstyle = "1.0.10"
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive", "wrap_help"] }
glob = "0.3.1"
indoc = "2.0.5"
insta = { version = "1.41.1", features = ["glob"] }
miette = { version = "7.3.0", default-features = false }
mimalloc = "0.1.43"
proc-macro2 = { version = "1.0.92", default-features = false }
quote = { version = "1.0.37", default-features = false }
rustc-hash = "2.0.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
syn = "2.0.89"
thiserror = "2.0.3"

[profile.release]
lto = "thin"
strip = true
