[graph]
all-features = true

[advisories]
ignore = ["RUSTSEC-2024-0436"]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
]

[bans]
skip = [
    "bitflags@1",
    "getrandom@0.2",
    "heck@0.4",
    "unicode-width@0.1",
]
