[graph]
all-features = true

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]

[bans]
skip = [
    "bitflags@1",
    "getrandom@0.2",
    "heck@0.4",
    "thiserror@1",
    "thiserror-impl@1",
    "unicode-width@0.1",
    "wasi@0.11",
]
