[graph]
all-features = true

[advisories]
version = 2

[licenses]
version = 2
allow = [
	"Apache-2.0",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"ISC",
	"MIT",
]
exceptions = [
    { allow = ["MPL-2.0"], name = "option-ext" },
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
]

[bans]
skip = [
    { name = "bitflags", version = "1" },
    { name = "heck", version = "0.4" },
]
skip-tree = [
    { name = "windows-sys", version = "0.48", depth = 3 },
]
