consolidate-commits = true
sign-commit = true
sign-tag = true
shared-version = true

pre-release-commit-message = "chore(release): release {{crate_name}} {{version}}"
tag-message = "chore(release): release {{crate_name}} {{version}}"
