[default]
extend-ignore-re = [
    '\[[[:xdigit:]]{7}\]\(https://github.com/dnaka91/mabo/commit/[[:xdigit:]]{40}\)',
]

[default.extend-identifiers]
froms = "froms"
relateds = "relateds"
vALUE = "vALUE"

[type.cargo-insta]
extend-glob = ["*.snap", "*.snap.new"]
check-file = false
