[package]
name = "stef-lsp"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ouroboros = "0.18.0"
stef-compiler = { path = "../stef-compiler" }
stef-parser = { path = "../stef-parser" }
tokio = { version = "1.34.0", features = ["io-std", "macros", "rt-multi-thread"] }
tower-lsp = { version = "0.20.0", features = ["proposed"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

[lints]
workspace = true
