[book]
title = "STEF - Strongly Typed Encoding Format"
authors = ["Dominik Nakamura"]
description = "Strongly Typed Encoding Format"
language = "en"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/dnaka91/stef"

[output.html.playground]
runnable = false
