name: Book
on:
  push:
    branches: [main]
    paths: ["book/**"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install cargo-binstall
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-binstall
      - name: Install tools
        run: cargo binstall --no-confirm lychee@0.13.0 mdbook@0.4.32 mdbook-toc@0.14.0
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Build Book
        run: mdbook build book
      - name: Check links
        run: lychee 'book/src/**/*.md' 'book/book/**/*.html'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: book/book
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
